ERROR:root:01-10-2019_14_46_59 Bad File Extension://dtnas1hq/users/leonard.santoro//Project Docs/users
Traceback (most recent call last):
  File "sort_files.py", line 30, in sort_files_in_a_folder
    filetype=file.split('.')[1]
IndexError: list index out of range
ERROR:root:01-10-2019_15_10_29 Bad File Extension://dtnas1hq/users/leonard.santoro//Project Docs/users
Traceback (most recent call last):
  File "sort_files.py", line 30, in sort_files_in_a_folder
    filetype=file.split('.')[1]
IndexError: list index out of range
ERROR:root:Exception Occured
Traceback (most recent call last):
  File "sort_files.py", line 21, in sort_files_in_a_folder
    files = [f for f in listdir(mypath) if isfile(join(mypath, f))]
FileNotFoundError: [WinError 53] The network path was not found: '//dtnas1hq/users/leonard.santoro'
ERROR:root:Exception Occured
Traceback (most recent call last):
  File "sort_files.py", line 21, in sort_files_in_a_folder
    files = [f for f in listdir(mypath) if isfile(join(mypath, f))]
FileNotFoundError: [WinError 53] The network path was not found: '//dtnas1hq/users/leonard.santoro//Project Docs'
ERROR:root:Exception Occured
Traceback (most recent call last):
  File "sort_files.py", line 21, in sort_files_in_a_folder
    files = [f for f in listdir(mypath) if isfile(join(mypath, f))]
FileNotFoundError: [WinError 53] The network path was not found: '//dtnas1hq/users/leonard.santoro//Personal'
ERROR:root:01-10-2019_22_01_46Exception Occured
Traceback (most recent call last):
  File "sort_files.py", line 21, in sort_files_in_a_folder
    files = [f for f in listdir(mypath) if isfile(join(mypath, f))]
FileNotFoundError: [WinError 53] The network path was not found: '//dtnas1hq/users/leonard.santoro'
ERROR:root:01-10-2019_22_02_12Exception Occured
Traceback (most recent call last):
  File "sort_files.py", line 21, in sort_files_in_a_folder
    files = [f for f in listdir(mypath) if isfile(join(mypath, f))]
FileNotFoundError: [WinError 53] The network path was not found: '//dtnas1hq/users/leonard.santoro//Project Docs'
ERROR:root:01-10-2019_22_02_12Exception Occured
Traceback (most recent call last):
  File "sort_files.py", line 21, in sort_files_in_a_folder
    files = [f for f in listdir(mypath) if isfile(join(mypath, f))]
FileNotFoundError: [WinError 53] The network path was not found: '//dtnas1hq/users/leonard.santoro//Personal'
ERROR:root:02-10-2019_09_44_02 Bad File Extension://dtnas1hq/users/leonard.santoro//Project Docs/users
Traceback (most recent call last):
  File "sort_files.py", line 31, in sort_files_in_a_folder
    filetype=file.split('.')[1]
IndexError: list index out of range
ERROR:root:03-10-2019_18_06_36 Bad File Extension://dtnas1hq/users/leonard.santoro//Project Docs/users
Traceback (most recent call last):
  File "sort_files.py", line 31, in sort_files_in_a_folder
    filetype=file.split('.')[1]
IndexError: list index out of range
ERROR:root:04-10-2019_09_17_53 Bad File Extension://dtnas1hq/users/leonard.santoro//Project Docs/users
Traceback (most recent call last):
  File "sort_files.py", line 31, in sort_files_in_a_folder
    filetype=file.split('.')[1]
IndexError: list index out of range
INFO:root:04-10-2019_17_29_06 File Cleaner Completed
INFO:root:04-10-2019_18_43_34 File Cleaner Completed
INFO:root:04-10-2019_18_44_16 File Cleaner Completed
INFO:root:07-10-2019_10_00_24 File Cleaner Completed
INFO:root:07-10-2019_17_49_09 File Cleaner Completed
